-- 全てのテーブルのPK/FK
SELECT 
    C.Table_Name,
    C.Column_Name,
    LEFT(PK.CONSTRAINT_NAME, 2) AS COLUMN_KEY,
    PK.CONSTRAINT_NAME
FROM
    Information_Schema.COLUMNS C
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE PK
ON C.TABLE_NAME = PK.TABLE_NAME
AND
   C.COLUMN_NAME = PK.COLUMN_NAME
AND 
   C.TABLE_SCHEMA = PK.TABLE_SCHEMA
 WHERE PK.CONSTRAINT_NAME IS NOT NULL

--StockItemテーブルにFKありますか。
SELECT 
    C.Table_Name,
    C.Column_Name,
    LEFT(PK.CONSTRAINT_NAME, 2) AS COLUMN_KEY,
    PK.CONSTRAINT_NAME
FROM
    Information_Schema.COLUMNS C
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE PK
ON C.TABLE_NAME = PK.TABLE_NAME
AND
   C.COLUMN_NAME = PK.COLUMN_NAME
AND 
   C.TABLE_SCHEMA = PK.TABLE_SCHEMA
 WHERE C.TABLE_NAME = 'dimStockItem'
 AND PK.CONSTRAINT_NAME IS NOT NULL


--テーブル件数
SELECT 
    COUNT(*)
FROM dimStockItem

